services:
  db:
    image: postgres:14-alpine
    restart: always
    env_file:
      - .env.development
    environment:
      POSTGRES_DB: medsmart
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    restart: always
    ports:
      - '6379:6379'

  localstack:
    image: localstack/localstack:latest
    restart: always
    environment:
      - SERVICES=s3,sqs
      - DEFAULT_REGION=${AWS_REGION}
    ports:
      - '4566:4566'



volumes:
  pgdata:
  localstack_data:
